# Generated by Django 2.2.5 on 2019-09-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_approved_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_comment',
            new_name='approved_comments',
        ),
    ]
